############################
## CHANGE THESE
############################

baseURL: "https://thrzty.com"
title: thrzty

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
