############################
## Author
############################

author:
  name: thrzty
  image: thrzty.jpeg
  greeting: "multimedia artist at your service"
  icon: ":wave:"

############################
## Links
############################

links:
  # - github: https://github.com/spudunk/thrzty
  # - link: https://github.com/spudunk/thrzty#readme
  - link: https://thrzty.com
  # - website: https://thrzty.com
  # - x-twitter:
  # - mastodon:
  # - linkedin:
  - instagram: https://www.instagram.com/thrzty
  - reddit: https://www.reddit.com/user/thrzty/
  # - telegram:
  # - whatsapp:
  # - signal:
  # - codepen:
  # - dev:
  # - email:
  # - discord:
  # - orcid:
  # - slack:
  # - stack-overflow:
  - twitch: https://www.twitch.tv/thrzty
  # - patreon:
  - soundcloud: https://soundcloud.com/thrzty
  # - dribbble:
  # - stack-exchange:
  # - tiktok:
  # - youtube:
  # - keybase:
  # - flickr:
  # - tumblr:
  # - kickstarter:
  # - snapchat:
  # - bluesky:
  # - bitbucket:
  # - bandcamp:
  # - etsy:
  - spotify: https://open.spotify.com/user/salixprolixa
  # - pinterest:
  # - strava:
  # - untappd:
  # - skype:
  # - medium:
  # - foursquare:
  # - apple:
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: thrzty
description: "multimedia artist at your service"
images:
  - thrzty.jpeg
